-- PHASE 0: BULLDOZER - Clean Slate
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

-- 1. DESTROY EXISTING TABLES
DROP TABLE IF EXISTS task_backlog CASCADE;
DROP TABLE IF EXISTS secrets_vault CASCADE;
DROP TABLE IF EXISTS lessons_learned CASCADE;
DROP TABLE IF EXISTS agent_tasks CASCADE;

-- 2. REBUILD PER PRD

-- CORE TASK QUEUE
CREATE TABLE task_backlog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  result JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE
);

-- SECRETS VAULT
CREATE TABLE secrets_vault (
  id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  key_name TEXT UNIQUE,
  encrypted_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CORPORATE BRAIN
CREATE TABLE lessons_learned (
  id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  task_id BIGINT REFERENCES task_backlog(id),
  lesson TEXT,
  context TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- AGENT TASK QUEUE
CREATE TABLE agent_tasks (
  id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  agent_name TEXT,
  task_type TEXT,
  payload JSONB,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  result JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- 3. ENABLE RLS (Row Level Security)
ALTER TABLE task_backlog ENABLE ROW LEVEL SECURITY;
ALTER TABLE secrets_vault ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons_learned ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_tasks ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICIES (Service role bypasses RLS, so this is for anon/authenticated)
CREATE POLICY "Allow all for service role" ON task_backlog FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON secrets_vault FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON lessons_learned FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON agent_tasks FOR ALL USING (true);

-- 5. INDEXES FOR PERFORMANCE
CREATE INDEX idx_task_backlog_status ON task_backlog(status);
CREATE INDEX idx_task_backlog_created ON task_backlog(created_at);
CREATE INDEX idx_agent_tasks_status ON agent_tasks(status);
CREATE INDEX idx_agent_tasks_agent ON agent_tasks(agent_name);

-- DONE. Fresh schema ready for VibePilot.
